# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(511, 271)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(511, 271))
        MainWindow.setMaximumSize(QSize(511, 271))
        font = QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionExit.setFont(font)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionAbout.setFont(font)
        self.actionUserGuide = QAction(MainWindow)
        self.actionUserGuide.setObjectName(u"actionUserGuide")
        self.actionUserGuide.setFont(font)
        self.actionOpen_Log = QAction(MainWindow)
        self.actionOpen_Log.setObjectName(u"actionOpen_Log")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(True)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(2, 0, 507, 221))
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.tabWidget.setFont(font1)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideNone)
        self.MainTab = QWidget()
        self.MainTab.setObjectName(u"MainTab")
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(False)
        self.MainTab.setFont(font2)
        self.MainTab.setAutoFillBackground(True)
        self.label = QLabel(self.MainTab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 31, 31))
        self.label.setFont(font2)
        self.logLineEdit = QLineEdit(self.MainTab)
        self.logLineEdit.setObjectName(u"logLineEdit")
        self.logLineEdit.setEnabled(True)
        self.logLineEdit.setGeometry(QRect(40, 20, 366, 31))
        self.logLineEdit.setFont(font2)
        self.logLineEdit.setStyleSheet(u"")
        self.logLineEdit.setReadOnly(True)
        self.selectButton = QPushButton(self.MainTab)
        self.selectButton.setObjectName(u"selectButton")
        self.selectButton.setGeometry(QRect(420, 20, 71, 31))
        self.selectButton.setFont(font2)
        self.line = QFrame(self.MainTab)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 70, 521, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_2 = QLabel(self.MainTab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 100, 81, 31))
        self.label_2.setFont(font2)
        self.periodLineEdit = QLineEdit(self.MainTab)
        self.periodLineEdit.setObjectName(u"periodLineEdit")
        self.periodLineEdit.setGeometry(QRect(100, 100, 121, 31))
        self.periodLineEdit.setFont(font2)
        self.periodLineEdit.setStyleSheet(u"")
        self.periodLineEdit.setFrame(True)
        self.periodLineEdit.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.label_3 = QLabel(self.MainTab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(280, 100, 81, 31))
        self.label_3.setFont(font2)
        self.bufferLineEdit = QLineEdit(self.MainTab)
        self.bufferLineEdit.setObjectName(u"bufferLineEdit")
        self.bufferLineEdit.setGeometry(QRect(370, 100, 121, 31))
        self.bufferLineEdit.setFont(font2)
        self.bufferLineEdit.setStyleSheet(u"border-color: rgb(0, 0, 255);")
        self.label_4 = QLabel(self.MainTab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 150, 71, 31))
        self.label_4.setFont(font2)
        self.drawButton = QPushButton(self.MainTab)
        self.drawButton.setObjectName(u"drawButton")
        self.drawButton.setGeometry(QRect(420, 150, 71, 31))
        self.drawButton.setFont(font2)
        self.drawButton.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.drawButton.setAutoDefault(False)
        self.comboBox = QComboBox(self.MainTab)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QRect(90, 150, 311, 31))
        self.comboBox.setFont(font2)
        self.comboBox.setFrame(True)
        self.tabWidget.addTab(self.MainTab, "")
        self.UserGuideTab = QWidget()
        self.UserGuideTab.setObjectName(u"UserGuideTab")
        sizePolicy.setHeightForWidth(self.UserGuideTab.sizePolicy().hasHeightForWidth())
        self.UserGuideTab.setSizePolicy(sizePolicy)
        self.UserGuideTab.setAutoFillBackground(True)
        self.guideTextEdit = QTextEdit(self.UserGuideTab)
        self.guideTextEdit.setObjectName(u"guideTextEdit")
        self.guideTextEdit.setGeometry(QRect(0, 0, 505, 191))
        sizePolicy.setHeightForWidth(self.guideTextEdit.sizePolicy().hasHeightForWidth())
        self.guideTextEdit.setSizePolicy(sizePolicy)
        self.guideTextEdit.setFont(font2)
        self.guideTextEdit.setStyleSheet(u"")
        self.guideTextEdit.setFrameShape(QFrame.Shape.Panel)
        self.guideTextEdit.setFrameShadow(QFrame.Shadow.Sunken)
        self.guideTextEdit.setReadOnly(True)
        self.tabWidget.addTab(self.UserGuideTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 511, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen_Log)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionUserGuide)
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ADTM Tool", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionUserGuide.setText(QCoreApplication.translate("MainWindow", u"User Guide", None))
        self.actionOpen_Log.setText(QCoreApplication.translate("MainWindow", u"Open Log", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"File:", None))
        self.selectButton.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Period Time", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Buffer Time", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Alsa Node", None))
        self.drawButton.setText(QCoreApplication.translate("MainWindow", u"Draw", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MainTab), QCoreApplication.translate("MainWindow", u"Main", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.UserGuideTab), QCoreApplication.translate("MainWindow", u"User Guide", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

